ODS-5550 Packages - EdFi.Db.Deploy workflow added
Ed-Fi-Alliance-OSS/Ed-Fi-Databases pull request #21
Opened 2022-10-04 22:26 UTC by semalaiappan

2022-10-05 21:26 UTC, bptillman requested changes
Just a few small changes to make and then this should be good to go.

2022-10-06 13:30 UTC, semalaiappan commented on .github/workflows/Packages - EdFi.Db.Deploy.yml
> +    inputs:
Removed it . Thanks

2022-10-06 14:07 UTC, semalaiappan commented on .github/workflows/Packages - EdFi.Db.Deploy.yml
> +    - name: unit tests
I moved to powershell script file .Thanks

2022-10-06 14:51 UTC, bptillman approved these changes

2022-10-06 14:52 UTC, merged